const CARS = [
  // --- SUPERCARS ---
  {
    slug: "lamborghini-revuelto",
    name: "Lamborghini Revuelto",
    brand: "Lamborghini",
    year: 2024,
    transmission: "Automatic",
    fuel: "Hybrid",
    seats: 2,
    engine: "6.5L V12",
    drivetrain: "AWD",
    interior: "Leather & Alcantara",
    quote: "Hybrid rage meets V12 symphony for road and track.",
    description: "The Revuelto combines hybrid power with a pure V12 soul. Its lightweight carbon-fiber chassis ensures razor-sharp handling while advanced active aerodynamics adapt to every corner. The driver-focused cockpit features digital instrumentation and premium materials. With cutting-edge hybrid technology, it delivers breathtaking acceleration, exceptional top speed, and a thrilling driving experience both on track and on the open road.",
    image: "Supercars-and-cars/lamborghini-revuelto-hero.avif",
    perf: { zeroTo100: "3.0s", powerKW: 606, topSpeed: "350 km/h" }
  },
  {
    slug: "ferrari-sf90",
    name: "Ferrari SF90",
    brand: "Ferrari",
    year: 2024,
    transmission: "Automatic",
    fuel: "Hybrid",
    seats: 2,
    engine: "4.0L V8 + electric",
    drivetrain: "AWD",
    interior: "Leather & Carbon-fibre trim",
    quote: "Electric boost, V8 fury, Ferrari precision everywhere.",
    description: "The SF90 blends a roaring V8 engine with three electric motors, delivering instantaneous acceleration and razor-sharp precision. Its minimalist yet luxurious cabin focuses on driver engagement, while advanced aerodynamics and cutting-edge technology ensure unmatched performance. From tight corners to open straights, the SF90 offers an exhilarating and unforgettable driving experience.",
    image: "Supercars-and-cars/ferrari-sf90-hero.avif",
    perf: { zeroTo100: "2.5s", powerKW: 735, topSpeed: "340 km/h" }
  },
  {
    slug: "maserati-gt2-stradale",
    name: "Maserati GT2 Stradale",
    brand: "Maserati",
    year: 2024,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 2,
    engine: "4.0L V8",
    drivetrain: "RWD",
    interior: "Leather",
    quote: "Race-bred Maserati drama, tailored for the street.",
    description: "GT2 Stradale brings track excitement to the road with a thrilling V8 engine, precise handling, and advanced aerodynamics. Its unforgettable acoustic tone, sharp set-up, and iconic Italian design turn heads wherever you go, offering an exhilarating driving experience for both road and track enthusiasts.",
    image: "Supercars-and-cars/maserati-gt2stradale-hero.avif",
    perf: { zeroTo100: "2.8s", powerKW: 471, topSpeed: "324 km/h" }
  },

  // --- MERCEDES ---
  {
    slug: "mercedes-a-class-2024",
    name: "Mercedes A-Class 2024",
    brand: "Mercedes",
    year: 2024,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "2.0L I4",
    drivetrain: "FWD",
    interior: "MB-Tex / Leatherette",
    quote: "Compact luxury with effortless tech.",
    description: "The A-Class delivers a truly refined driving experience, combining a stylish and modern interior with advanced infotainment systems, intuitive controls, and efficient petrol performance. Designed for city commutes, weekend getaways, and daily driving, it offers comfort, smooth handling, and a quiet cabin. Premium materials, ergonomic seating, and smart connectivity enhance every journey, making it a perfect blend of practicality, luxury, and technology for modern drivers.",
    image: "Mercedes-cars/a-class-2024.jpg"
  },
  {
    slug: "mercedes-c-class-2024",
    name: "Mercedes C-Class 2024",
    brand: "Mercedes",
    year: 2024,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "2.0L I4",
    drivetrain: "RWD",
    interior: "Leather",
    quote: "Luxury meets performance in a mid-size sedan.",
    description: "C-Class seamlessly combines timeless elegance, cutting-edge technology, and smooth driving dynamics to provide a superior premium experience. Its luxurious cabin features high-quality materials, ambient lighting, and an intuitive infotainment system. The responsive engine options and precise handling make both urban streets and highway cruising effortless, while advanced safety features ensure confidence and peace of mind. Designed for those who demand style, comfort, and performance, C-Class elevates every journey with sophistication and practicality.",
    image: "Mercedes-cars/c-class-2024.webp"
  },
  {
    slug: "mercedes-e-class-2024",
    name: "Mercedes E-Class 2024",
    brand: "Mercedes",
    year: 2024,
    transmission: "Automatic",
    fuel: "Diesel",
    seats: 5,
    engine: "2.0L I4 Diesel",
    drivetrain: "RWD",
    interior: "Leather",
    quote: "Executive comfort and advanced technology.",
    description: "E-Class offers a spacious and elegant cabin, equipped with the latest intuitive technology, advanced driver assistance systems, and efficient diesel engine options. Every detail is designed for comfort, including plush seating, refined materials, and ambient lighting. Long-distance journeys are effortless thanks to smooth ride quality, superior handling, and smart connectivity features. Combining style, luxury, and performance, the E-Class ensures that drivers and passengers alike enjoy every moment on the road, whether commuting or traveling across countries.",
    image: "Mercedes-cars/e-class-2024.avif"
  },
  {
    slug: "mercedes-s63-class-2024",
    name: "Mercedes S63 Class 2024",
    brand: "Mercedes",
    year: 2024,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "4.0L V8",
    drivetrain: "RWD",
    interior: "Nappa Leather",
    quote: "Top-tier luxury and performance.",
    description: "S63 Class embodies the pinnacle of luxury, offering lavish interiors, meticulously crafted materials, and cutting-edge technology. Its powerful engine delivers thrilling performance while maintaining smooth and comfortable ride quality. Advanced driver-assist features, adaptive suspension, and intuitive controls enhance both safety and driving pleasure. Every journey is a statement of prestige, with spacious seating, premium entertainment systems, and a serene cabin environment. The S63 Class blends performance, innovation, and elegance for those who demand uncompromising excellence on every drive.",
    image: "Mercedes-cars/s-class-2024.avif"
  },
  {
    slug: "mercedes-gle-63s-amg-2024",
    name: "Mercedes GLE 63S AMG 2024",
    brand: "Mercedes",
    year: 2024,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "4.0L V8",
    drivetrain: "AWD",
    interior: "Nappa Leather",
    quote: "Performance SUV with luxury styling.",
    description: "GLE 63S AMG combines exhilarating sporty performance with luxurious and spacious interiors, delivering a unique driving experience for families and enthusiasts alike. Its powerful engine, adaptive suspension, and advanced handling systems ensure dynamic agility on any terrain. The cabin features premium materials, advanced infotainment, and ample cargo space for everyday convenience. With cutting-edge safety features, connectivity options, and a commanding presence, the GLE 63S AMG offers an ideal balance of power, comfort, and versatility for all driving adventures.",
    image: "Mercedes-cars/gle-2024.avif"
  },
  {
    slug: "mercedes-g63-amg-2024",
    name: "Mercedes G63 AMG 2024",
    brand: "Mercedes",
    year: 2024,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "4.0L V8 Biturbo",
    drivetrain: "AWD",
    interior: "Premium Leather",
    quote: "Iconic off-road luxury.",
    description: "G63 AMG blends legendary off-road prowess with refined luxury, offering a commanding presence on any terrain. Its robust engine and advanced 4x4 system tackle rough landscapes effortlessly while maintaining smooth on-road performance. Inside, occupants enjoy premium leather seating, sophisticated technology, and a spacious cabin. Innovative safety and infotainment systems enhance both comfort and confidence. Designed for adventure and elegance, G63 AMG provides unmatched versatility, turning every drive—urban or rugged—into an exceptional experience of power, style, and sophistication.",
    image: "Mercedes-cars/g63-amg-2024.webp"
  },

  // --- AUDI ---
  {
    slug: "audi-a4-2024",
    name: "Audi A4 2024",
    brand: "Audi",
    year: 2024,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "2.0L I4",
    drivetrain: "FWD",
    interior: "Leather",
    quote: "Compact executive with style.",
    description: "A4 offers sporty handling, comfortable interior, and advanced tech features, making it a versatile choice for everyday driving. Its cabin combines premium materials, ergonomic seating, and intuitive infotainment to ensure both comfort and connectivity. From city streets to long highway journeys, the A4 delivers precise control, smooth ride quality, and impressive efficiency, providing a balanced and enjoyable driving experience for executives and enthusiasts alike.",
    image: "Audi-cars/audi-a4-sedan-2024.webp"
  },
  {
    slug: "audi-a6-2024",
    name: "Audi A6 2024",
    brand: "Audi",
    year: 2024,
    transmission: "Automatic",
    fuel: "Diesel",
    seats: 5,
    engine: "3.0L V6 Diesel",
    drivetrain: "FWD",
    interior: "Leather",
    quote: "Mid-size luxury with performance.",
    description: "A6 combines smooth diesel performance with elegant interior design and cutting-edge tech for a refined driving experience. It features spacious seating, ambient lighting, advanced infotainment, and driver assistance systems. The sedan is ideal for both professional and personal use, delivering comfort, efficiency, and a premium feel on every journey.",
    image: "Audi-cars/audi-a6-sedan-2024.avif"
  },
  {
    slug: "audi-a8-2024",
    name: "Audi A8 2024",
    brand: "Audi",
    year: 2024,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "3.0L V6",
    drivetrain: "AWD",
    interior: "Leather",
    quote: "Full-size executive luxury.",
    description: "A8 delivers top-level comfort, advanced technology, and powerful petrol performance for long-distance travel in style. Luxurious materials, refined seats, ambient lighting, and a sophisticated infotainment system provide an unmatched executive experience. Its smooth ride and responsive handling make it perfect for both city and highway driving.",
    image: "Audi-cars/audi-a8-sedan-2024.jpg"
  },
  {
    slug: "audi-q5-2024",
    name: "Audi Q5 2024",
    brand: "Audi",
    year: 2024,
    transmission: "Automatic",
    fuel: "Hybrid",
    seats: 5,
    engine: "2.0L I4 Hybrid",
    drivetrain: "AWD",
    interior: "Leather",
    quote: "Hybrid SUV with efficiency.",
    description: "Q5 blends hybrid efficiency with comfortable interior and versatile space, ideal for family trips or daily commutes. The cabin features ergonomic seating, smart infotainment, and ample cargo room. Smooth driving dynamics and fuel-efficient hybrid power make the Q5 both practical and enjoyable to drive.",
    image: "Audi-cars/audi-q5-2024.avif"
  },
  {
    slug: "audi-q7-2024",
    name: "Audi Q7 2024",
    brand: "Audi",
    year: 2024,
    transmission: "Automatic",
    fuel: "Diesel",
    seats: 7,
    engine: "3.0L V6 Diesel",
    drivetrain: "AWD",
    interior: "Leather",
    quote: "Spacious SUV for family trips.",
    description: "Q7 provides seven seats, modern safety features, and diesel efficiency, perfect for family adventures or long drives. Its premium cabin, advanced infotainment, and adaptive suspension deliver both comfort and performance. With generous cargo space and versatile seating arrangements, the Q7 accommodates families and luggage effortlessly, making every journey smooth and enjoyable.",
    image: "Audi-cars/audi-q7-7seats-2024.avif"
  },
  {
    slug: "audi-q8-e-tron-2024",
    name: "Audi Q8 e-Tron 2024",
    brand: "Audi",
    year: 2024,
    transmission: "Automatic",
    fuel: "Electric",
    seats: 5,
    engine: "Electric",
    drivetrain: "AWD",
    interior: "Leather",
    quote: "Electric SUV with modern tech.",
    description: "Q8 e-Tron delivers fully electric power, spacious cabin, and smart tech, perfect for eco-conscious urban driving. Its elegant interior, advanced infotainment, and adaptive systems provide comfort, connectivity, and convenience. Zero-emission driving meets premium SUV luxury, offering both performance and sustainability for modern lifestyles.",
    image: "Audi-cars/audi-q8-etron-2024-version2.webp"
  },

  // --- BMW ---
  {
    slug: "bmw-3-series-2024",
    name: "BMW 3 Series 2024",
    brand: "BMW",
    year: 2024,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "2.0L I4",
    drivetrain: "RWD",
    interior: "Leather",
    quote: "Sporty executive sedan.",
    description: "3 Series offers dynamic handling, comfort, and modern tech, making daily drives enjoyable and sporty. The cabin is crafted with premium materials and ergonomic seating. Advanced infotainment and driver-assistance systems enhance safety and convenience, making the 3 Series ideal for professionals seeking both performance and refinement.",
    image: "BMW-cars/bmw-3-series-2024.jpg"
  },
  {
    slug: "bmw-5-series-2024",
    name: "BMW 5 Series 2024",
    brand: "BMW",
    year: 2024,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "3.0L I6",
    drivetrain: "RWD",
    interior: "Leather",
    quote: "Executive sedan with performance.",
    description: "5 Series blends luxury, petrol performance, and spacious interior for both city and highway driving. Its refined cabin, advanced infotainment, and adaptive suspension offer comfort and responsive handling. Safety features, premium materials, and ample cargo space make it an ideal executive sedan for everyday use or long-distance travel.",
    image: "BMW-cars/bmw-5-series-2024.jpg"
  },
  {
    slug: "bmw-7-series-2024",
    name: "BMW 7 Series 2024",
    brand: "BMW",
    year: 2024,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "4.4L V8",
    drivetrain: "RWD",
    interior: "Luxury Leather",
    quote: "Full-size luxury sedan.",
    description: "7 Series offers high-end technology, smooth petrol engine, and luxurious interior for executive comfort. Plush seating, ambient lighting, cutting-edge infotainment, and advanced driver assistance systems create an unparalleled driving experience. Long journeys are effortless thanks to adaptive suspension, precise handling, and silent cabin design.",
    image: "BMW-cars/bmw-7-series-2024-v2.avif"
  },
  {
    slug: "bmw-x5-2024",
    name: "BMW X5 2024",
    brand: "BMW",
    year: 2024,
    transmission: "Automatic",
    fuel: "Hybrid",
    seats: 5,
    engine: "3.0L I6 Hybrid",
    drivetrain: "AWD",
    interior: "Leather",
    quote: "Hybrid SUV with tech.",
    description: "X5 combines hybrid power with roomy interior and modern features for family-friendly driving. Comfortable seating, ample cargo space, and advanced infotainment make daily use and long trips convenient and enjoyable. Efficient hybrid system ensures performance with reduced emissions, while all-wheel-drive and adaptive suspension provide confident handling on various terrains.",
    image: "BMW-cars/bmw-x5-2024.avif"
  },
  {
    slug: "bmw-x7-2024",
    name: "BMW X7 2024",
    brand: "BMW",
    year: 2024,
    transmission: "Automatic",
    fuel: "Diesel",
    seats: 7,
    engine: "3.0L I6 Diesel",
    drivetrain: "AWD",
    interior: "Leather",
    quote: "Diesel-powered full-size SUV.",
    description: "X7 provides seven seats, diesel efficiency, and comfort for family and long-distance journeys. Its premium interior, advanced safety systems, and adaptive suspension offer a smooth and controlled ride. Spacious cabin and cargo capacity make it ideal for large families or extended trips, while maintaining BMW's signature driving dynamics.",
    image: "BMW-cars/bmw-x7-7seats-2024.jpg"
  },
  {
    slug: "bmw-i4-2024",
    name: "BMW i4 2024",
    brand: "BMW",
    year: 2024,
    transmission: "Automatic",
    fuel: "Electric",
    seats: 5,
    engine: "Electric",
    drivetrain: "RWD",
    interior: "Leatherette / Leather option",
    quote: "Electric sporty sedan.",
    description: "i4 offers full electric driving, sporty handling, and modern technology for efficient city and highway driving. Its interior features premium materials, ergonomic seating, and advanced infotainment. With zero-emission performance, instantaneous torque, and precise handling, i4 combines sustainability with excitement in a luxury sedan package.",
    image: "BMW-cars/bmw-i4-2024.avif"
  },

// --- JEEP ---
{
    slug: "jeep-wrangler-2024",
    name: "Jeep Wrangler 2024",
    brand: "Jeep",
    year: 2024,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "3.6L V6",
    drivetrain: "4x4",
    interior: "Durable Leather / Cloth",
    quote: "Iconic off-road SUV.",
    description: "Wrangler combines legendary off-road capability with modern comfort and technology, offering unmatched versatility for every adventure. Its rugged 4x4 drivetrain, durable suspension, and high ground clearance allow it to tackle the toughest terrains with ease, while the refined interior provides ergonomic seating, advanced infotainment, and smart safety features. Perfect for off-road enthusiasts and explorers, the Wrangler ensures both thrilling outdoor experiences and comfortable daily driving.",
    image: "Jeep-cars/jeep-wrangler-2024.avif"
  },
  {
    slug: "jeep-grand-cherokee-2024",
    name: "Jeep Grand Cherokee 2024",
    brand: "Jeep",
    year: 2024,
    transmission: "Automatic",
    fuel: "Diesel",
    seats: 5,
    engine: "3.0L V6 Diesel",
    drivetrain: "4x4",
    interior: "Leather",
    quote: "Spacious off-road SUV.",
    description: "Grand Cherokee offers a perfect blend of diesel efficiency, luxurious comfort, and formidable off-road capability, making it ideal for both family journeys and adventurous escapes. Its robust 4x4 system, advanced suspension, and high ground clearance allow it to tackle challenging terrains with confidence, while the spacious interior features premium materials, modern infotainment, and smart safety technologies. Whether navigating city streets or exploring rugged landscapes, the Grand Cherokee ensures a smooth, versatile, and enjoyable driving experience for every occasion.",
    image: "Jeep-cars/jeep-grand-cherokee-2024.avif"
  },
  {
    slug: "jeep-compass-2021",
    name: "Jeep Compass 2021",
    brand: "Jeep",
    year: 2021,
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    engine: "2.0L I4",
    drivetrain: "FWD",
    interior: "Cloth / Leather optional",
    quote: "Compact SUV with style.",
    description: "Compass delivers agile handling, practical features, and modern styling, making it an ideal companion for daily urban driving. Its compact yet versatile design ensures effortless maneuverability through city streets and tight parking spaces, while the comfortable interior provides advanced infotainment, smart connectivity, and thoughtful storage solutions. With efficient performance, reliable safety systems, and stylish aesthetics, the Compass perfectly balances functionality and sophistication for drivers who seek both practicality and a touch of adventure in their everyday journeys.",
    image: "Jeep-cars/jeep-compass-2024.jpg"
  },
  {
    slug: "jeep-renegade-2021",
    name: "Jeep Renegade 2021",
    brand: "Jeep",
    year: 2021,
    transmission: "Automatic",
    fuel: "Hybrid",
    seats: 5,
    engine: "1.3L I4 Hybrid",
    drivetrain: "FWD",
    interior: "Cloth",
    quote: "Efficient compact SUV.",
    description: "Renegade blends hybrid efficiency with compact SUV practicality and comfort, making it perfect for both urban streets and suburban adventures. Its nimble size allows for effortless city maneuvering, while the thoughtfully designed interior offers modern infotainment, spacious seating, and versatile cargo space. Advanced safety features, efficient hybrid performance, and stylish design ensure a reliable, eco-friendly, and enjoyable driving experience for daily commutes, weekend getaways, or family outings.",
    image: "Jeep-cars/jeep-renegade-2021.avif"
  },
  {
    slug: "jeep-gladiator-2023",
    name: "Jeep Gladiator 2023",
    brand: "Jeep",
    year: 2023,
    transmission: "Automatic",
    fuel: "Diesel",
    seats: 5,
    engine: "3.6L V6 Diesel",
    drivetrain: "4x4",
    interior: "Durable Cloth / Leather trim",
    quote: "Durable pickup for all terrains.",
    description: "Gladiator provides robust diesel power, exceptional rugged durability, and versatile utility, making it perfect for both demanding work environments and thrilling off-road adventures. Its reinforced frame and advanced suspension handle rough terrains with ease, while the spacious cabin and modern tech ensure comfort and connectivity on every journey. Whether hauling equipment, exploring remote trails, or tackling daily tasks, the Gladiator delivers reliability, strength, and unmatched versatility for drivers who need a capable and adventurous pickup.",
    image: "Jeep-cars/jeep-gladiator-2023.avif"
  },
  {
    slug: "jeep-cherokee-2020",
    name: "Jeep Cherokee 2020",
    brand: "Jeep",
    year: 2024,
    transmission: "Automatic",
    fuel: "Diesel",
    seats: 5,
    engine: "2.0L I4",
    drivetrain: "AWD",
    interior: "Leather",
    quote: "Pickup SUV for rugged adventures.",
    description: "Cherokee delivers reliable petrol performance, practical interior space, and versatile SUV capabilities for everyday driving. Its comfortable cabin accommodates passengers and cargo with ease, while modern safety features and intuitive technology make city commutes and weekend trips enjoyable. Designed to handle both urban roads and light off-road adventures, the Cherokee combines efficiency, convenience, and dependability, making it an ideal choice for families and drivers seeking a balanced, all-purpose SUV.",
    image: "Jeep-cars/jeep-cherokee.avif"
  },

// --- VOLVO ---
{
    slug: "volvo-xc90-2023",
    name: "Volvo XC90 2023",
    brand: "Volvo",
    year: 2023,
    transmission: "Automatic",
    fuel: "Hybrid",
    seats: 7,
    engine: "2.0L I4 Hybrid",
    drivetrain: "AWD",
    interior: "Leather",
    quote: "Family-friendly hybrid SUV.",
    description: "The XC90 seamlessly combines hybrid efficiency with a spacious and luxurious interior, offering ample room for passengers and cargo. Equipped with advanced safety systems and cutting-edge technology, it ensures peace of mind on every journey. Its refined ride quality and versatile seating configurations make it perfect for family adventures, long-distance travel, or daily commutes, delivering comfort, practicality, and eco-conscious performance in one sophisticated package.",
    image: "Volvo-cars/volvo-xc90-2023.avif"
  },
  {
    slug: "volvo-xc60-2022",
    name: "Volvo XC60 2022",
    brand: "Volvo",
    year: 2022,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "2.0L I4",
    drivetrain: "FWD",
    interior: "Leather",
    quote: "Compact luxury SUV.",
    description: "The XC60 delivers a perfect balance of petrol-powered performance, refined comfort, and modern safety features, making it ideal for both daily commutes and weekend trips. Its spacious interior, intuitive infotainment system, and driver-assist technologies enhance convenience and security, while the smooth handling and responsive engine provide a confident and enjoyable driving experience. The XC60 combines practicality, style, and reliability for drivers seeking a versatile and sophisticated SUV.",
    image: "Volvo-cars/volvo-xc60-2022.avif"
  },
  {
    slug: "volvo-s90-2021",
    name: "Volvo S90 2021",
    brand: "Volvo",
    year: 2021,
    transmission: "Manual",
    fuel: "Diesel",
    seats: 5,
    engine: "2.0L I4 Diesel",
    drivetrain: "FWD",
    interior: "Leather",
    quote: "Executive diesel sedan.",
    description: "The S90 delivers an exceptional blend of diesel efficiency, refined luxury, and ultimate comfort, making it perfect for both professional and family use. Its spacious and meticulously crafted interior features premium materials, intuitive technology, and advanced driver-assistance systems, ensuring a safe and relaxing journey. The S90’s smooth ride, precise handling, and powerful diesel engine provide a confident driving experience, while its elegant design and sophisticated styling make a statement on the road. Combining performance, safety, and elegance, the S90 is an ideal executive sedan for discerning drivers.",
    image: "Volvo-cars/volvo-s90-2021.webp"
  },
  {
    slug: "volvo-v60-2020",
    name: "Volvo V60 2020",
    brand: "Volvo",
    year: 2020,
    transmission: "Manual",
    fuel: "Diesel",
    seats: 5,
    engine: "2.0L I4 Diesel",
    drivetrain: "FWD",
    interior: "Cloth / Practical trim",
    quote: "Practical wagon with diesel power.",
    description: "The V60 offers impressive diesel performance combined with versatile wagon space, making it ideal for daily life and family needs. Its thoughtfully designed interior provides comfort, practicality, and advanced technology, including intuitive infotainment and driver-assistance systems. With a smooth ride, efficient handling, and ample cargo capacity, the V60 is perfect for commuting, errands, and weekend adventures. Its sleek design, modern features, and reliable performance make it a practical yet stylish choice for drivers seeking both functionality and elegance.",
    image: "Volvo-cars/volvo-v60-2020.jpg"
  },
  {
    slug: "volvo-c40-recharge-2023",
    name: "Volvo C40 Recharge 2023",
    brand: "Volvo",
    year: 2023,
    transmission: "Automatic",
    fuel: "Electric",
    seats: 5,
    engine: "Electric",
    drivetrain: "AWD",
    interior: "Leather / Tech trim",
    quote: "Electric SUV with style.",
    description: "The C40 Recharge delivers a fully electric driving experience with zero emissions, combining cutting-edge technology and modern design. Its sleek, contemporary exterior is matched by a luxurious, tech-forward interior featuring intuitive infotainment, smart connectivity, and advanced driver-assistance systems. Designed for eco-conscious drivers, the C40 Recharge provides responsive handling, smooth acceleration, and impressive efficiency. Spacious and practical, it’s ideal for urban commuting, weekend trips, and environmentally responsible driving without compromising style or comfort.",
    image: "Volvo-cars/volvo-c40-recharge.jpg"
  },
  {
    slug: "volvo-xc40-2021",
    name: "Volvo XC40 2021",
    brand: "Volvo",
    year: 2021,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    engine: "2.0L I4",
    drivetrain: "FWD",
    interior: "Cloth / Leather option",
    quote: "Compact SUV with style.",
    description: "The XC40 offers a perfect blend of petrol efficiency, practicality, and style. Its modern interior is designed for comfort and versatility, providing ample storage and user-friendly technology. Advanced safety features ensure peace of mind for every journey, while the sleek and stylish exterior makes a statement in urban environments. Agile and responsive, the XC40 is ideal for city driving, weekend getaways, and everyday adventures, delivering both efficiency and driving enjoyment.",
    image: "Volvo-cars/volvo-xc40-2021.jpg"
  },
];
